<?php
/*
Plugin Name: Peleman AI Chatbot
Description: Adds a React-based Gemini AI chatbot to the footer of the website.
Version: 1.0
Author: Birhan Yorukoglu
*/

if (!defined('ABSPATH')) {
    exit; // Exit if accessed directly
}

// Autoloader for admin classes
spl_autoload_register(function ($class) {
    $prefix = 'PelemanChatbot\\';
    $base_dir = __DIR__ . DIRECTORY_SEPARATOR . 'adminPage' . DIRECTORY_SEPARATOR;
    
    $len = strlen($prefix);
    if (strncmp($prefix, $class, $len) !== 0) {
        return;
    }
    
    $relative_class = substr($class, $len);
    $file = $base_dir . str_replace('\\', DIRECTORY_SEPARATOR, $relative_class) . '.php';
    
    if (file_exists($file)) {
        require $file;
    }
}, true, true); // prepend=true, throw=true for better error handling

// Initialize Chatbot Tab Controller
function peleman_chatbot_init_plugin() {
    if (is_admin()) {
        // Require files directly to ensure they're loaded
        require_once __DIR__ . '/adminPage/Controllers/Chatbot_Tab_Controller.php';
        require_once __DIR__ . '/adminPage/Views/Peleman_Chatbot_Menu.php';
        
        // Initialize controller - it will add the filter if Peleman Products Extender is active
        new \PelemanChatbot\adminPage\Controllers\Chatbot_Tab_Controller();
    }
}
add_action('plugins_loaded', 'peleman_chatbot_init_plugin');

function peleman_enqueue_scripts() {
    // 1. Enqueue the React Build File
    // In a real build, this would point to 'dist/assets/index.js' generated by Vite/Webpack
    // For this example, we assume the build file is named 'peleman-chat.js'
    $js_file = plugin_dir_url(__FILE__) . 'dist/peleman-chat.js';
    $css_file = plugin_dir_url(__FILE__) . 'dist/peleman-chat.css';

    wp_enqueue_script('peleman-chat-js', $js_file, [], '1.0', true);
    wp_enqueue_style('peleman-chat-css', $css_file, [], '1.0');

    // 2. Pass Settings from PHP to React
    // This is how we securely pass the API Key or other WP settings to the frontend
    $brand_icon = plugin_dir_url(__FILE__) . 'assets/favicon.png';
    
    // Check if user is logged in
    $current_user = wp_get_current_user();
    $is_logged_in = $current_user->ID > 0;
    
    wp_localize_script('peleman-chat-js', 'pelemanSettings', [
        'apiKey' => get_option('peleman_gemini_api_key', ''), // Get from WP Database
        'siteUrl' => get_site_url(),
        'apiUrl' => rest_url('peleman-chatbot/v1'),
        'ajaxUrl' => admin_url('admin-ajax.php'),
        'brandIcon' => $brand_icon,
        'isLoggedIn' => $is_logged_in,
        'currentUser' => $is_logged_in ? [
            'id' => $current_user->ID,
            'name' => $current_user->display_name,
            'email' => $current_user->user_email
        ] : null,
        'loginUrl' => wp_login_url(get_permalink()) // Login sayfası URL'i
    ]);
}
add_action('wp_enqueue_scripts', 'peleman_enqueue_scripts');

// 2b. Expose WooCommerce catalog data over REST (now uses cache)
function peleman_get_catalog_data(WP_REST_Request $request) {
    if (!class_exists('WooCommerce')) {
        return new WP_Error('woocommerce_missing', 'WooCommerce is not active.', ['status' => 400]);
    }

    $lang = $request->get_param('lang') ?: 'nl';
    
    // Try to get cached catalog
    $cached = peleman_get_cached_catalog($lang);
    
    if ($cached) {
        return rest_ensure_response($cached);
    }
    
    // If no cache, generate and cache it
    $catalog_data = peleman_update_catalog_cache($lang);
    
    if ($catalog_data) {
        return rest_ensure_response($catalog_data);
    }
    
    return new WP_Error('catalog_error', 'Failed to generate catalog', ['status' => 500]);
}

function peleman_register_rest_routes() {
    register_rest_route('peleman-chatbot/v1', '/catalog', [
        'methods' => 'GET',
        'callback' => 'peleman_get_catalog_data',
        'permission_callback' => '__return_true'
    ]);
}
add_action('rest_api_init', 'peleman_register_rest_routes');

// Ensure the Vite build script is loaded as a module
function peleman_chatbot_script_type_module($tag, $handle, $src) {
    if ($handle === 'peleman-chat-js') {
        return '<script type="module" src="' . esc_url($src) . '"></script>';
    }
    return $tag;
}
add_filter('script_loader_tag', 'peleman_chatbot_script_type_module', 10, 3);

// 3. Add the Mount Point to the Footer
function peleman_add_root_div() {
    echo '<div id="peleman-chatbot-root" style="position: relative; z-index: 9999;"></div>';
}
add_action('wp_footer', 'peleman_add_root_div');

// Catalog cache functions
function peleman_get_cached_catalog($lang = null) {
    // If no lang specified, use current site language
    if (!$lang) {
        if (function_exists('pll_current_language')) {
            $lang = pll_current_language();
        } elseif (defined('ICL_LANGUAGE_CODE')) {
            $lang = ICL_LANGUAGE_CODE;
        } else {
            $lang = 'en'; // Default fallback
        }
    }
    
    $cache_key = 'peleman_catalog_cache_' . $lang;
    $cache_timestamp_key = 'peleman_catalog_cache_timestamp_' . $lang;
    
    $cached = get_option($cache_key);
    $timestamp = get_option($cache_timestamp_key, 0);
    
    // Check if cache is older than 24 hours
    if ($cached && $timestamp && (time() - $timestamp) < 86400) {
        return $cached;
    }
    
    return null;
}

function peleman_update_catalog_cache($lang = null) {
    if (!class_exists('WooCommerce')) {
        return false;
    }

    // Switch language if needed
    if ($lang) {
        if (function_exists('pll_switch_language')) {
            pll_switch_language($lang);
        }
        if (has_action('wpml_switch_language')) {
            do_action('wpml_switch_language', $lang);
        }
    }

    $categories = get_terms([
        'taxonomy' => 'product_cat',
        'hide_empty' => true
    ]);

    $category_data = array_map(function($term) {
        $thumbnail_id = get_term_meta($term->term_id, 'thumbnail_id', true);
        $thumbnail_url = $thumbnail_id ? wp_get_attachment_image_url($thumbnail_id, 'medium') : '';
        $term_link = get_term_link($term);

        return [
            'id' => (string) $term->slug,
            'name' => $term->name,
            'description' => $term->description,
            'thumbnail' => $thumbnail_url,
            'url' => is_wp_error($term_link) ? '' : $term_link
        ];
    }, $categories);

    // Get all published products (no limit to ensure all products are included)
    $products = wc_get_products([
        'status' => 'publish',
        'limit' => -1, // -1 means get all products, no pagination needed
        'orderby' => 'date',
        'order' => 'DESC',
        'return' => 'objects'
    ]);

    $product_data = array_map(function($product) {
        $category_ids = array_map('strval', $product->get_category_ids());
        $terms = $product->get_category_ids();
        $primary_cat = '';
        if (!empty($terms)) {
            $term = get_term($terms[0], 'product_cat');
            if ($term && !is_wp_error($term)) {
                $primary_cat = $term->slug;
            }
        }

        $attributes = [];
        foreach ($product->get_attributes() as $attr) {
            $options = [];
            if ($attr->is_taxonomy()) {
                $terms = $attr->get_terms();
                if (!is_wp_error($terms)) {
                    $options = array_map(function($term) {
                        return $term->name;
                    }, $terms);
                }
            } else {
                $options = $attr->get_options();
            }

            $attributes[] = [
                'name' => $attr->get_name(),
                'options' => $options
            ];
        }

        $image_id = $product->get_image_id();
        $image_url = $image_id ? wp_get_attachment_image_url($image_id, 'medium') : '';
        $product_url = get_permalink($product->get_id());

        return [
            'id' => (string) $product->get_id(),
            'name' => $product->get_name(),
            'category' => $primary_cat,
            'categoryIds' => array_values(array_filter(array_map(function($term_id) {
                $term = get_term($term_id, 'product_cat');
                return $term && !is_wp_error($term) ? $term->slug : '';
            }, $category_ids))),
            'description' => $product->get_short_description(),
            'image' => $image_url,
            'price' => wp_strip_all_tags($product->get_price_html()),
            'url' => $product_url,
            'attributes' => $attributes
        ];
    }, $products);

    $catalog_data = [
        'categories' => $category_data,
        'products' => $product_data
    ];

    $cache_key = 'peleman_catalog_cache_' . $lang;
    $cache_timestamp_key = 'peleman_catalog_cache_timestamp_' . $lang;
    
    update_option($cache_key, $catalog_data);
    update_option($cache_timestamp_key, time());
    
    return $catalog_data;
}

// Daily cron to update catalog cache for all active languages
function peleman_daily_catalog_update() {
    $languages = ['en', 'fr', 'es', 'nl']; // Your site languages
    
    foreach ($languages as $lang) {
        // Switch to language context
        if (function_exists('pll_switch_language')) {
            pll_switch_language($lang);
        }
        if (has_action('wpml_switch_language')) {
            do_action('wpml_switch_language', $lang);
        }
        
        peleman_update_catalog_cache($lang);
    }
}

// Schedule daily update
function peleman_schedule_daily_update() {
    if (!wp_next_scheduled('peleman_daily_catalog_update')) {
        wp_schedule_event(time(), 'daily', 'peleman_daily_catalog_update');
    }
}
add_action('wp', 'peleman_schedule_daily_update');
add_action('peleman_daily_catalog_update', 'peleman_daily_catalog_update');

// Manual update via AJAX - updates all languages
function peleman_ajax_update_catalog() {
    if (!current_user_can('manage_options')) {
        wp_send_json_error(['message' => 'Unauthorized']);
        return;
    }

    $languages = ['en', 'fr', 'es', 'nl'];
    $results = [];
    $errors = [];
    
    foreach ($languages as $lang) {
        // Switch to language context
        if (function_exists('pll_switch_language')) {
            pll_switch_language($lang);
        }
        if (has_action('wpml_switch_language')) {
            do_action('wpml_switch_language', $lang);
        }
        
        $result = peleman_update_catalog_cache($lang);
        if ($result) {
            $results[$lang] = get_option('peleman_catalog_cache_timestamp_' . $lang);
        } else {
            $errors[] = $lang;
        }
    }
    
    if (empty($errors)) {
        wp_send_json_success([
            'message' => 'All catalogs updated successfully',
            'timestamps' => $results
        ]);
    } else {
        wp_send_json_error([
            'message' => 'Some catalogs failed to update',
            'failed' => $errors,
            'success' => $results
        ]);
    }
}
add_action('wp_ajax_peleman_update_catalog', 'peleman_ajax_update_catalog');

// Enqueue admin scripts for AJAX (for catalog update functionality)
function peleman_admin_scripts($hook) {
    // Check if we're on Peleman Products Extender admin page
    if (strpos($hook, 'peleman-products-extender') !== false || strpos($hook, 'peleman') !== false) {
        wp_localize_script('jquery', 'ajaxurl', admin_url('admin-ajax.php'));
    }
}
add_action('admin_enqueue_scripts', 'peleman_admin_scripts');

// Initialize cache on plugin activation
function peleman_activate_plugin() {
    peleman_daily_catalog_update(); // Create initial cache
}
register_activation_hook(__FILE__, 'peleman_activate_plugin');
?>